[tool.poetry]
name = "seq4-botanist"
version = "0.1.0"
description = ""
authors = ["kenzie_academy_q4"]

[tool.poetry.dependencies]
python = "^3.8"
prettytable = "^2.1.0"
PTable = "^0.9.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
